<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (

  ),
);


/* End of file views.php */
/* Auto generated by Themes Administration on : 2012.12.26 19:58:33 */
/* Location: /Users/Partikule/Sites/02.Test/ionize-0.9.9/application/../themes/bootstrap/config/views.php */
